[phases.setup]
nixPkgs = ['bun', 'rustup', 'gcc', 'pkg-config', 'openssl', 'stdenv-linux']

[phases.build]
dependsOn = ['setup']
cmds = [
    'rustup default stable',
    'cd vallenato-acordeon-maestro && bun install && bun run build',
    'mkdir -p dist',
    'cp -r vallenato-acordeon-maestro/dist/* ./dist/',
    'cargo build --release && cp $(find ./target/release -maxdepth 1 -type f -executable -not -name "*.d") ./server-exec'
]

[start]
cmd = 'chmod +x ./server-exec && ./server-exec'