[phases.setup]
nixPkgs = ['bun', 'rustup', 'gcc', 'pkg-config', 'openssl']

[phases.build]
dependsOn = ['setup']
cmds = [
    'rustup default stable',
    'cd vallenato-acordeon-maestro && bun install && bun run build',
    'mkdir -p dist',
    'cp -r vallenato-acordeon-maestro/dist/* ./dist/',
    'cargo build --release'
]

[start]
cmd = './target/release/pagina_andrea_vallenato'