ALTER TABLE user_courses
ALTER COLUMN purchased_at TYPE TIMESTAMPTZ
USING purchased_at AT TIME ZONE 'UTC';

ALTER TABLE user_courses
ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE user_courses
ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
